USERNAME='root'
PASSWORD=''
DBNAME='laravel_projet'
HOST='localhost'
COLLATE_DB='utf8mb4_unicode_ci'
ENCODAGE_DB='utf8mb4'

USER_USERNAME='edi'
USER_PASSWORD='edi'

MySQL=$(cat <<EOF
DROP DATABASE IF EXISTS $DBNAME;
CREATE DATABASE $DBNAME DEFAULT CHARACTER SET $ENCODAGE_DB COLLATE $COLLATE_DB;
DELETE FROM mysql.user WHERE user='$USER_USERNAME' and host='$USER_PASSWORD';
GRANT ALL PRIVILEGES ON $DBNAME.* to '$USER_USERNAME'@'$HOST' IDENTIFIED BY '$USER_PASSWORD' WITH GRANT OPTION;
EOF
)

echo $MySQL | mysql --user=$USERNAME --password=$PASSWORD

php artisan migrate:refresh --seed